version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
